src/Entity/Country.php
<?php

namespace App\Entity;

use App\Repository\CountryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CountryRepository::class)]
class Country
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    /**
     * @var Collection<int, Movie>
     */
    #[ORM\OneToMany(targetEntity: Movie::class, mappedBy: 'country')]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): static
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->setCountry($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): static
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getCountry() === $this) {
                $movie->setCountry(null);
            }
        }

        return $this;
    }
}

src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GenreRepository::class)]
class Genre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $title = null;

    /**
     * @var Collection<int, Movie>
     */
    #[ORM\OneToMany(targetEntity: Movie::class, mappedBy: 'genre')]
    private Collection $movies;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): static
    {
        if (!$this->movies->contains($movie)) {
            $this->movies->add($movie);
            $movie->setGenre($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): static
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getGenre() === $this) {
                $movie->setGenre(null);
            }
        }

        return $this;
    }
}

src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(length: 2000)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $runtime = null;

    #[ORM\Column]
    private ?int $budget = null;

    #[ORM\Column(length: 250)]
    private ?string $poster = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\ManyToOne(inversedBy: 'movies')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Genre $genre = null;

    #[ORM\ManyToOne(inversedBy: 'movies')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Country $country = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRuntime(): ?int
    {
        return $this->runtime;
    }

    public function setRuntime(int $runtime): static
    {
        $this->runtime = $runtime;

        return $this;
    }

    public function getBudget(): ?int
    {
        return $this->budget;
    }

    public function setBudget(int $budget): static
    {
        $this->budget = $budget;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): static
    {
        $this->country = $country;

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;


use App\Entity\Movie;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class MovieController extends AbstractController
{
    public function __construct(private readonly EntityManagerInterface $entityManager)
    {
    }

    #[Route('/movies', name: 'app_controlador_peliculas')]
    public function index():Response
    {
        //para poder acceder al MovieRepository que es el lugar donde se guardan las queries
        $movies = $this->entityManager->getRepository(Movie::class)->findAll();
        return $this->render('movie/index.html.twig',['movies' => $movies, 'title' => 'Peliculas']
        );
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/movie/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <div class="bg-gray-900 py-16">
        <div class="container mx-auto px-4">
            <h1 class="text-6xl text-white text-center">
                <i class="fas fa-film"></i>Movies<i class="fas fa-film"></i>
            </h1>
        </div>
    </div>
        <div class="container mx-auto px-4 py-8">
            {% if movies is empty %}
            <div class="bg-white rounded-lg shadow-lg overflow-hidden relative">
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">No movies found</div>
                </div>
                <p class="text-gray-700 text base">
                    There are no movies at this moment. <a href="#" class="text-blue-500">Add one</a>
                </p>
            </div>
        </div>
            {% else %}
                <div class="grid grid-cols-3 gap-4">
                    {% for movie in movies %}
                    <div class="bg-white rounded-lg shadow-lg overflow-hidden relative">
                        <a href="#">
                            <img class="w-full h-56 object-cover object-center" src="{{ movie.poster }}" alt="Imagen no disponible">
                        </a>
                    </div>
                    <div class="px-4 py-4">
                        <div class="font-bold text-xl mb-2">{{ movie.title }}</div>
                        <p class="text-gray-700 text-base">
                            {{ movie.description|slice(0,100) }}
                        </p>

                        {# el include es como llamar al archivo para que usar todo su contenido
                        lo del with es solamente para corroborar que tiene que user la variable movie#}
                        <div class="flex-justify-center mt2">
                            {%  include 'partials/movies/facts.html.twig' with {'movie':movie}%}
                        </div>
                            <div class="flex justify-center my-3">
                                <a href="#" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-l">
                                    <i class="fas fa-edit"></i>Edit
                                </a>
                                <a href="#" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4">
                                    <i class="fas fa-eye"></i>View
                                </a>

                            </div>

                {% endfor %}
                </div>
            {% endif %}
    </div>
{% endblock %}

templates/partials/movies/facts.html.twig
<div class="facts">
                                <span class="release text-sm text-gray-600 bg-gray-200 p-2">
                                    <i class="fas fa-calendar-alt"></i>{{ movie.releaseDate|date('d/m/Y') }}
                                </span>
    <span class="runtime text-sm text-gray-600 bg-gray-200 p-2">
                                    <i class="fas fa-clock"></i>{{ movie.runtime }} min
                                </span>
    <span class="budget text-sm text-gray-600 bg-gray-200 p-2">
                                    <i class="fas fa-dollar-sign"></i> {{ movie.budget|number_format(0, ',', '.') }}
                                </span>
    {# para acceder a una elemento enlazado hay que la entity en la que se encuentra #}
    <span class="budget text-sm text-gray-600 bg-gray-200 p-2">
                                    <i class="fas fa-globe"></i> {{ movie.country.name }}
                                </span>
    <span class="budget text-sm text-gray-600 bg-gray-200 p-2">
                                    <i class="fas fa-film"></i> {{ movie.genre.title }}
                                </span>
</div>